$Script:GPOConfiguration = [ordered] @{
    GPOBroken                    = $GPORevOrphans
    GPOBrokenLink                = $GPORevBrokenLink
    GPOOwners                    = $GPORevOwners
    GPOConsistency               = $GPORevConsistency
    GPODuplicates                = $GPORevDuplicates
    GPOOrganizationalUnit        = $GPORevOrganizationalUnit
    GPOList                      = $GPORevList
    GPOLinks                     = $GPORevLinks
    GPOPassword                  = $GPORevPassword
    GPOPermissions               = $GPORevPermissionsAnalysis
    GPOPermissionsAdministrative = $GPORevPermissionsAdministrative
    GPOPermissionsRead           = $GPORevPermissionsRead
    GPOPermissionsRoot           = $GPORevPermissionsRoot
    GPOPermissionsUnknown        = $GPORevPermissionsUnknown
    GPORedirect                  = $GPORevGPORedirects
    GPOFiles                     = $GPORevFiles
    GPOBlockedInheritance        = $GPORevBlockedInheritance
    GPOAnalysis                  = $GPORevAnalysis
    GPOUpdates                   = $GPORevGPOUpdates
    NetLogonOwners               = $GPORevNetLogonOwners
    NetLogonPermissions          = $GPORevNetLogonPermissions
    SysVolLegacyFiles            = $GPORevSysVolLegacyFiles
}